---
# yamllint disable rule:empty-lines

{# import macros to use in this template #}
{% import "macros/macros.j2" as macros %}

{# Define global namespace to track jobs that were added to the pipeline
# the variables set here will become populated as the pipeline is set
#
# all      - will contain all jobs created by this pipeline
# tests    - a dictionary where the 3 keys are a subset of tests needed for passing conditions
#            The three keys are the following
#              - 'basic' - the initial set of testing jobs (used by the testing gate)
#              - 'extended' - the set of extended tests (used by the compatibility gate)
#              - 'backward_compatibility' - all backward compatibility tests (used by the promotion gate)
#
# The following variables get reset after each gate in anticipation of the next gate:
# images        - a dictionary where the image resource name is the key and the value is a list of tests the image has passed
#                     ex: {'gpdb6-pxf-dev-centos7-image': ['test-pxf-gp6-ext-hdp2-centos7']} could be in the dictionary
# tarballs      - a dictionary where the tarball resource name is the key and the value is a list of tests the tarball has passed
# gpdb_packages - a dictionary where the Greenplum package resource name is the key and the value is a list of tests it has passed
#}
{% set job_names = namespace(all=[], tests={'basic':[], 'extended':[], 'backward_compatibility':[]}, images={}, tarballs={}, gpdb_packages={}) %}

{# define supported test features (single-cluster test jobs) and whether their testing is requested by the Makefile via context variables #}
{% set requested_features = {'s3': s3, 'gs': gs, 'abfss': abfss, 'wasbs': wasbs, 'minio': minio, 'hdp2': hdp2, 'hdp3': hdp3, 'cdh': cdh, 'jdk11': jdk11} %}
{% set supported_features = requested_features.keys() | list %}

{#
# ======================================================================
# BUILD and TEST Combinations for PXF
# ======================================================================

# gp_ver        : major Greenplum version
# build_os      : the name of the OS used to build PXF artifacts
# test_os       : the name of the OS used to test  PXF artifacts
# os_ver        : the version of the OS
# test_fdw      : whether to test PXF FDW extension in this configuration
# test_file     : whether to test PXF with FILE protocol in this configuration
# test_cli      : whether to test PXF CLI functionality in this configuration
# test_multi    : whether to test PXF against multi-node Hadoop clusters in this configuration
# test_features : an array of features to test PXF with in this configuration
#
# when iterating over the entries, use the following pattern:
# {% call(x) macros.for_each_config(build_test_pxf_combinations) %}
#     <do whatever rendering you need for a combination, can use {% include '.../some-template.yml' %} >
# {% endcall %}
#}

{% set build_test_pxf_combinations = [
    {'gp_ver': '5', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': [], 'generate_release_tarball': true},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7',     'test_fdw': false, 'test_file': true , 'test_cli': false, 'test_multi': true , 'test_features': supported_features + ['upgrade-extension'], 'generate_release_tarball': true},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8',     'test_fdw': true , 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': [], 'generate_release_tarball': false},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': true , 'test_features': [], 'generate_release_tarball': false},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'oel'   , 'os_ver': '7',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': [], 'generate_release_tarball': false},
    {'gp_ver': '6', 'build_os': 'ubuntu', 'test_os': 'ubuntu', 'os_ver': '18.04', 'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': [], 'generate_release_tarball': false},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8',     'test_fdw': true , 'test_file': false, 'test_cli': true , 'test_multi': true , 'test_features': ['upgrade-extension'], 'generate_release_tarball': false},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9',     'test_fdw': false, 'test_file': false, 'test_cli': false, 'test_multi': false, 'test_features': [], 'generate_release_tarball': false}] %}


{# define supported clouds that have their own 'protocols' #}
{% set clouds = ['s3', 'gs', 'abfss', 'wasbs', 'minio'] %}

{# define distros we use for singlecluster setup #}
{% set distros = ['hdp2', 'hdp3', 'cdh'] %}

{# define default distro and impersonation for all test jobs #}
{% set default_distro = 'hdp2' %}
{% set default_impers = 'true' %}

{% set gp_num_versions = { '5': num_gpdb5_versions, '6': num_gpdb6_versions, '7': num_gpdb7_versions} %}

{# Build a list of supported test platforms using the configuration matrix above
# This will also separately build a list of release repackages images needed for each platform.
#
# As we do not produce an OEL artifact, the pxf_release_repackage_images dictionary will not
# have an entry for OEL. However, it is considered a supported test platform.
#}
{% set supported_test_platforms = [] %}
{% set pxf_release_repackage_images = {} %}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_platform not in supported_test_platforms %}
    {# get the list of all platforms that we test against #}
    {% do supported_test_platforms.append(x.test_platform) %}
    {% endif%}

    {# get the list of all platforms that we build against and the image needed release repackaging on that platform #}
    {% do pxf_release_repackage_images.update({ x.build_platform : x.pxf_release_repackage_image}) %}
{% endcall %}
{% set supported_build_platforms = pxf_release_repackage_images.keys() | list %}

{# ensure that there are no jobs initially in the list, additionally, initialize any necessary lists #}
[[macros.reset_passed_jobs(build_test_pxf_combinations, job_names)]]

## ======================================================================
## ANCHORS
## ======================================================================
anchors:
    [[macros.anchor_destroy_dataproc(1)]]
    [[macros.anchor_destroy_dataproc(2)]]
    [[macros.anchor_destroy_cluster('gpdb')]]
    [[macros.anchor_destroy_cluster('ipa-hadoop')]]
    [[macros.anchor_gchat_notification(gchat_notification)]]

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:
    [[macros.resource_type_registry_image('terraform', 'gcr.io/data-gpdb-ud/terraform-resource', '0.11.15')]]
    [[macros.resource_type_registry_image('terraform-0.14.10', 'ljfranklin/terraform-resource', '0.14.10')]]
    [[macros.resource_type_registry_image('gcs', 'gcr.io/data-gpdb-public-images/gcs-resource', '')]]
    [[macros.resource_type_registry_image('google-chat-notify-resource', 'springio/google-chat-notify-resource', '0.0.1-SNAPSHOT')]]

## ======================================================================
## RESOURCES
## ======================================================================
resources:
    [[macros.resource_pxf_dependencies('build')]]
    [[macros.resource_pxf_dependencies('automation')]]

## ---------- Single Cluster tarballs ----------
    [[macros.resource_singlecluster('hdp2')]]
    [[macros.resource_singlecluster('hdp3')]]
    [[macros.resource_singlecluster('cdh')]]

## ---------- Github Repos ----------
    [[macros.resource_github_repo('pxf')]]
    [[macros.resource_github_repo('ccp')]]

## ---------- RelEng Drop Artifacts ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/release-artifact-tpl.yml' %}
{% endcall %}

{% call(x) macros.for_each_gp_ver(build_test_pxf_combinations) %}
    {% include 'resources/release-osl-odp-tpl.yml' %}
{% endcall %}

## ---------- RelEng Drop Artifacts for tarballs ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.generate_release_tarball is sameas true %}
        {% include 'resources/release-tarball-artifact-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- PXF ShipIt resources ----------
[[macros.shipit_file(environment)]]

## ---------- Docker Images ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-test-image-tpl.yml' %}
{% endcall %}

{% for build_platform in supported_build_platforms %}
    {% if build_platform != 'ubuntu18.04' %}
    [[macros.resource_registry_image('rpmrebuild-' ~ build_platform ~ '-image', 'gcr.io/data-gpdb-ud/rpmrebuild-' ~ build_platform, 'latest')]]
    {% endif %}
{% endfor %}

    [[macros.resource_registry_image('ccp-7-image', 'gcr.io/data-gpdb-public-images/ccp', 'latest')]]

    [[macros.resource_registry_image('google-cloud-sdk-slim-image', 'google/cloud-sdk', '402.0.0-slim')]]

## ---------- Google Chat Notification ----------
{% if gchat_notification %}
    {% if environment == 'prod' %}
        [[macros.resource_gchat_notification('gchat-alert', 'gchat-gp-extended-federation-ci-webhook')]]
        [[macros.resource_gchat_notification('notify-releng', 'gchat-gp-extended-ci-webhook')]]
    {% else %}
        [[macros.resource_gchat_notification('gchat-alert', 'gchat-' ~ user ~ '-ci-webhook')]]
        [[macros.resource_gchat_notification('notify-releng', 'gchat-' ~ user ~ '-ci-webhook')]]
    {% endif %}
{% endif %}

## ---------- Greenplum Packages ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% do x.update({'gp_num_versions': gp_num_versions[x.gp_ver]}) %}
    {% include 'resources/greenplum-package-tpl.yml' %}
{% endcall %}

## ---------- PXF Artifacts ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-artifact-tpl.yml' %}
{% endcall %}

## ---------- PXF 5 Artifact ---------------
    [[macros.resource_pxf5_gp6_el7_artifact()]]

## ---------- PXF 6.MINOR Artifact ---------------
# These are for pxf and pxf_fdw extension upgrade testing.
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf6_minor-rpm-artifact-tpl.yml' %}
{% endcall %}

## ---------- Auxiliary Resources ----------
    [[macros.resource_terraform('gpdb')]]
    [[macros.resource_terraform('ipa-hadoop')]]

## ======================================================================
## JOBS
## ======================================================================
jobs:

## ---------- Build and Basic Singlenode Test Swimlanes ----------
{# include a build job for all OS other than OEL (which does not have a separate build job) #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_os != 'oel' %}
        {% include 'jobs/build-tpl.yml' %}
        {% set job_names.all = job_names.all + [x.job_name] %}
    {% endif %}
{% endcall %}

{# include a non-FDW test job for all OS #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% do x.update({'use_fdw': 'false'}) %}
    {% do x.update({'use_impers': default_impers}) %}
    {% do x.update({'target': default_distro}) %}
    {% do x.update({'distro': default_distro}) %}
    [[macros.add_test_job('jobs/test-tpl.yml', x, job_names, 'basic', gchat_notification)]]
{% endcall %}

{# include an FDW test job if supported by the swimlane #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_fdw is sameas true %}
        {% do x.update({'use_fdw': 'true'}) %}
        {% do x.update({'use_impers': default_impers}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        [[macros.add_test_job('jobs/test-tpl.yml', x, job_names, 'basic', gchat_notification)]]
    {% endif %}
{% endcall %}

## ---------- Testing Gate ----------
[[macros.add_gate_job('jobs/testing-gate-tpl.yml', job_names, environment, build_test_pxf_combinations, pxf_release_repackage_images, gchat_notification)]]

[[macros.reset_passed_jobs(build_test_pxf_combinations, job_names)]]

## ---------- Extended Feature (clouds, distros, jdk) tests ----------
{# include a non-FDW test job for all clouds if supported #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% do x.update({ 'passed': '[testing-gate-for-pxf-gp]' }) %}
    {# iterate over features defined for the given swimlane #}
    {% for test_feature in x.test_features %}
        {% do x.update({'use_fdw': 'false'}) %}

        {# if the purpose of the test is to try a different distro/cloud, use it, otherwise use a default distro for the job name #}
        {% set target = test_feature if (test_feature in distros or test_feature in clouds) else default_distro %}
        {% do x.update({'target': target}) %}

        {# set the distro to use for the test job's single cluster, use default if the feature are not a distro #}
        {% set distro = test_feature if test_feature in distros else default_distro %}
        {% do x.update({'distro': distro}) %}

        {# request a no-impers job for clouds and the default distro (as basic test job is default distro with impersonation) #}
        {% set use_impers = 'false' if (test_feature in clouds or test_feature == default_distro) else 'true' %}
        {% do x.update({'use_impers': use_impers}) %}

        {# define a protocol if the feature is a cloud test #}
        {% set protocol = test_feature if test_feature in clouds else '' %}
        {% do x.update({'protocol': protocol}) %}

        {# define a feature name to go into the test job name, unless it is a test against a distro/cloud only #}
        {% set feature = test_feature if test_feature not in distros and test_feature not in clouds else '' %}
        {% do x.update({'feature': feature}) %}

        {# for upgrade-extension only, use a different job definition #}
        {% set job_infix = '-upgrade-extension' if test_feature == 'upgrade-extension' else '' %}
        [[macros.add_test_job('jobs/test' ~ job_infix ~'-tpl.yml', x, job_names, 'extended', gchat_notification)]]

        {# for S3 only, also include an additional impersonation job #}
        {% if test_feature == 's3' %}
            {% do x.update({'use_impers': 'true'}) %}
            [[macros.add_test_job('jobs/test-tpl.yml', x, job_names, 'extended', gchat_notification)]]
        {% endif %}
    {% endfor %}
{% endcall %}

## ---------- FILE tests -----------------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_file is sameas true %}
        {% do x.update({'passed': '[testing-gate-for-pxf-gp]'}) %}
        {% do x.update({'distro': default_distro}) %}
        [[macros.add_test_job('jobs/test-file-tpl.yml', x, job_names, 'extended', gchat_notification)]]
    {% endif %}
{% endcall %}

## ---------- GP7 PXF CLI tests ----------
{# include a CLI test, for now Makefile only defines the switch for GP7 #}
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
  {% if x.test_cli %}
  {% do x.update({'passed': '[testing-gate-for-pxf-gp]'}) %}
        [[macros.add_test_job('jobs/test-cli-tpl.yml', x, job_names, 'extended', gchat_notification)]]
    {% endif %}
{% endcall %}

## ---------- Multi-node tests ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.test_multi is sameas true %}
        {% do x.update({'use_fdw': 'false'}) %}
        {% do x.update({'use_impers': 'true'}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}

        {# include upgrade task when running on centos7 only #}
        {% set with_upgrade = 'true' if x.test_platform == 'centos7' else 'false' %}
        {% do x.update({'with_upgrade': with_upgrade}) %}

        {% do x.update({'passed': '[testing-gate-for-pxf-gp]'}) %}
        [[macros.add_test_job('jobs/test-multinode-tpl.yml', x, job_names, 'extended', gchat_notification)]]
    {% endif %}
    {# multinode no impersonation job for now will only be for GP6 with Centos7 #}
    {% if x.test_multi is sameas true and x.gp_ver == '6' and x.test_platform == 'centos7' %}
        {% do x.update({'use_fdw': 'false'}) %}
        {% do x.update({'use_impers': 'false'}) %}
        {% do x.update({'target': default_distro}) %}
        {% do x.update({'distro': default_distro}) %}
        {% do x.update({'with_upgrade': 'false'}) %}
        [[macros.add_test_job('jobs/test-multinode-tpl.yml', x, job_names, 'extended', gchat_notification)]]
    {% endif %}
{% endcall %}

## ---------- Compatibility Gate ----------
[[macros.add_gate_job('jobs/compatibility-gate-tpl.yml', job_names, environment, build_test_pxf_combinations, pxf_release_repackage_images, gchat_notification)]]

[[macros.reset_passed_jobs(build_test_pxf_combinations, job_names)]]

## ---------- Compatibility Testing ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% do x.update({'gp_num_versions': gp_num_versions[x.gp_ver]}) %}
    {# number of backwards compatibility tasks that can run at once #}
    {% do x.update({'max_concurrent_bc_tasks': 3}) %}
    {% if x.test_os != 'oel' %}
        [[macros.add_test_job('jobs/test-backward-compatibility-tpl.yml', x, job_names, 'backward_compatibility', gchat_notification)]]
    {% endif %}
{% endcall %}

## ---------- Artifact Promotion Gate ----------
[[macros.add_gate_job('jobs/promote-pxf-artifacts-tpl.yml', job_names, environment, build_test_pxf_combinations, pxf_release_repackage_images, gchat_notification)]]

## ---------- Artifact Publication Gate ----------
[[macros.add_gate_job('jobs/publish-pxf-artifacts-tpl.yml', job_names, environment, build_test_pxf_combinations, pxf_release_repackage_images, gchat_notification)]]

## ======================================================================
## GROUPS
## ======================================================================
groups:
- name: all
  jobs:
    [[job_names.all]]

{% for platform in supported_test_platforms %}
    [[macros.job_group(platform, job_names.all)]]
{% endfor %}

{% call(x) macros.for_each_gp_ver(build_test_pxf_combinations) %}
    [[macros.job_group('gp' ~ x.gp_ver, job_names.all)]]
{% endcall %}
