on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.9.0 (12/08/2023)

            ### Enhancements:

            - [#1035](https://github.com/greenplum-db/pxf/pull/1035) Upgrade snappy-java to 1.1.10.4
            - [#1040](https://github.com/greenplum-db/pxf/pull/1040) Bump golang.org/x/net from 0.7.0 to 0.17.0 in /cli
            - [#1044](https://github.com/greenplum-db/pxf/pull/1044) Upgrade Go toolchain to 1.21.3
            - [#1058](https://github.com/greenplum-db/pxf/pull/1058) Add RHEL9 Support

            ### Bug Fixes:

            - [#1047](https://github.com/greenplum-db/pxf/pull/1047) Fix pxf register command

          draft: false
          prerelease: false
